// nextjs/app/components/Navbar.tsx
export default function Navbar() {
  return (
    <nav className="sticky top-0 z-50 bg-white border-b border-gray-200 py-4">
      <div className="max-w-240 mx-auto px-5 flex justify-between items-center">
        <a href="#" className="text-2xl font-bold text-red-700 uppercase">
          NewsPortal
        </a>
        <ul className="flex gap-5 list-none m-0 p-0">
          <li><a href="#" className="text-sm font-bold text-gray-800 uppercase hover:text-red-700">Home</a></li>
          <li><a href="#" className="text-sm font-bold text-gray-800 uppercase hover:text-red-700">Politics</a></li>
          <li><a href="#" className="text-sm font-bold text-gray-800 uppercase hover:text-red-700">Tech</a></li>
          <li><a href="#" className="text-sm font-bold text-gray-800 uppercase hover:text-red-700">Sports</a></li>
          <li><a href="#" className="text-sm font-bold text-gray-800 uppercase hover:text-red-700">Lifestyle</a></li>
        </ul>
      </div>
    </nav>
  );
}

// Nuxtjs/src/components/Navbar.vue
<template>
  <nav class="navbar">
    <div class="navbar-container">
      <a href="#" class="logo">NewsPortal</a>
      <ul class="nav-links">
        <li><a href="#">Home</a></li>
        <li><a href="#">Politics</a></li>
        <li><a href="#">Tech</a></li>
        <li><a href="#">Sports</a></li>
        <li><a href="#">Lifestyle</a></li>
      </ul>
    </div>
  </nav>
</template>

<script setup>
</script>
